service: supportai-ai-prod

frameworkVersion: '4'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    PORT: ${env:PORT}

  architecture: arm64
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'il-central-1'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin
